# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DamageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Jump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('score', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiREST.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Resistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='SuperMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=30)),
                ('image', models.FileField(upload_to='super-mode')),
            ],
        ),
        migrations.CreateModel(
            name='Velocity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='damage_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiREST.DamageLevel'),
        ),
        migrations.AddField(
            model_name='character',
            name='health',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiREST.Health'),
        ),
        migrations.AddField(
            model_name='character',
            name='jump',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiREST.Jump'),
        ),
        migrations.AddField(
            model_name='character',
            name='resistance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiREST.Resistance'),
        ),
        migrations.AddField(
            model_name='character',
            name='super_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiREST.SuperMode'),
        ),
        migrations.AddField(
            model_name='character',
            name='velocity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiREST.Velocity'),
        ),
    ]
