# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0002_auto_20170913_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='photo_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
