# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0003_character_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='nombre',
            new_name='name',
        ),
    ]
