# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0004_auto_20171002_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='entrant',
            field=models.CharField(default=2017, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='graduate',
            field=models.CharField(default=2017, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supermode',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
