# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0006_auto_20171025_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
    ]
