# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0007_alternative_is_true'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='entrant',
        ),
        migrations.RemoveField(
            model_name='player',
            name='graduate',
        ),
        migrations.AddField(
            model_name='player',
            name='finish_year',
            field=models.CharField(default='2017-01', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='initial_year',
            field=models.CharField(default='2017-01', max_length=10),
        ),
    ]
