# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiREST', '0010_stage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='finish_year',
            field=models.CharField(default='2019-01', max_length=10),
        ),
    ]
